server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-03742505.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa90i7kntYAvGn0y5d7
            client-secret: A41E3Df4hyzYelv1fwyOF3lYZzgzRjZVaM9mYUO4
        provider:
          okta:
            issuer-uri: https://dev-03742505.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-half-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-slide: 10
        sliding-window-type: COUNT_BASED